// Wired Ethernet on the Olimex ESP32-POE, and UDP out (platform layer, R4).
#pragma once

#include <stddef.h>
#include <stdint.h>

#include "esp_err.h"
#include "wfb_core.hpp"

// Olimex ESP32-POE pin map (#16): LAN8720 PHY at address 0, MDC 23, MDIO 18, PHY power 12, and the
// RMII clock generated by the ESP32 on GPIO17. (The ESP32-POE-WROVER moves the clock to GPIO0.)
struct eth_config
{
    int phy_addr = 0;
    int mdc_gpio = 23;
    int mdio_gpio = 18;
    int power_gpio = 12;
    int clock_out_gpio = 17;
};

// Starts Ethernet with DHCP and waits up to timeout_ms for an address. Call after radio_start(),
// which creates the default event loop.
esp_err_t eth_start(const eth_config &config, int timeout_ms);

// Times the Ethernet link went down since it first came up: a sign of an unstable RMII clock, which
// the ESP32 errata warns about with Wi-Fi on (#18).
uint32_t eth_link_drops(void);

// Sends each payload as one UDP datagram to host:port (R5): the receiver's payloads go to the NUC.
class udp_out : public wfb_payload_sink
{
public:
    esp_err_t open(const char *host, uint16_t port);
    void send_payload(const uint8_t *buf, size_t size) override;

    uint32_t sent = 0, failed = 0;

private:
    int fd = -1;
    uint8_t addr[16] = {};  // struct sockaddr_in, kept opaque so this header needs no lwIP
};
